---
- name: Set Homebrew homebrew_user variable
  ansible.builtin.set_fact:
    homebrew_user: "{{ homebrew_user | default(ansible_user_id) }}"
    homebrew_group: "{{ homebrew_group | default(ansible_user_gid) }}"
  tags:
    - always

- name: Ensure the homebrew parent directory has the correct permissions
  ansible.builtin.file:
    group: "{{ ansible_user_gid }}"
    mode: "0755"
    owner: "{{ ansible_user_id }}"
    path: "{{ homebrew_prefix }}/.."
    state: directory

- name: Collect package manager facts
  ansible.builtin.setup:
    filter: ansible_pkg_mgr
  tags:
    - always

- name: Escalate privileges if Homebrew user is not the user running the playbook
  block:

    - name: Ensure brew is updated
      ansible.builtin.command: "{{ homebrew_bin_path }}/brew update --force"

    - name: Query brew for the Homebrew cache location
      ansible.builtin.command: "{{ homebrew_bin_path }}/brew --cache"
      register: homebrew_cache_path
      changed_when: False
      check_mode: False
      tags:
        - always

    - name: Ensure configured taps are tapped
      community.general.homebrew_tap:
        tap: "{{ item.name | default(item) }}"
        url: "{{ item.url | default(omit) }}"
        state: present
      loop: "{{ homebrew_taps }}"
      tags:
        - taps

    # Casks
    - name: Ensure blacklisted cask applications are not installed
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: absent
        sudo_password: "{{ ansible_become_password | default(omit) }}"
      loop: "{{ homebrew_cask_uninstalled_apps }}"
      tags:
        - casks

    - name: Ensure required cask applications are installed
      community.general.homebrew_cask:
        name: "{{ homebrew_required_casks }}"
        state: present
        accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
        sudo_password: "{{ ansible_become_password | default(omit) }}"
      notify:
        - Clear homebrew cache
      tags:
        - casks

    # Packages
    - name: Ensure blacklisted Homebrew packages are not installed
      community.general.homebrew:
        name: "{{ homebrew_uninstalled_packages }}"
        state: absent
      register: results
      tags:
        - packages

    - name: Display the results of `brew uninstall`
      ansible.builtin.debug:
        msg: "{{ results.msg }}"

    - name: Ensure required Homebrew packages are installed
      community.general.homebrew:
        name: "{{ homebrew_required_packages }}"
        state: present
      register: results
      notify:
        - Clear homebrew cache
      tags:
        - packages

    - name: Display the results of `brew install`
      ansible.builtin.debug:
        msg: "{{ results.msg }}"

    - name: Upgrade all Homebrew packages
      community.general.homebrew:
        update_homebrew: True
        upgrade_all: True
      when: homebrew_upgrade_all_packages | bool
      notify:
        - Clear homebrew cache
      tags:
        - packages

    - name: Check for Brewfile
      ansible.builtin.stat:
        path: "{{ homebrew_brewfile_dir }}/Brewfile"
      register: homebrew_brewfile
      check_mode: False
      when: homebrew_use_brewfile | bool
      tags:
        - always

    - name: Install from Brewfile
      ansible.builtin.command: "{{ homebrew_bin_path }}/brew bundle chdir={{ homebrew_brewfile_dir }}"
      when: homebrew_brewfile.stat.exists and homebrew_use_brewfile | bool
      tags:
        - packages

  # Privilege escalation is only required for inner steps when
  # the `homebrew_user` doesn't match the `ansible_user_id`
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
